### PR TITLE
SUS-649 limit chat message length

### PR DESCRIPTION
**Pull request by mixth-sense**
## Description

Up until today, maximum length of a chat message has been set [on the client](https://github.com/Wikia/app/blob/dev/extensions/wikia/Chat2/js/controllers/controllers.js#L121). Then somebody managed to set it to `infinity` and started posting lengthy messages with lots of emojis which killed all clients' performance.

The point is to introduce maximum limit, which I did in the model. And then I applied the limit in the server code. Finally, I added user-friendly handling of the event on the client side.

## Ticket & other links

* http://wikia-inc.atlassian.net/browse/SUS-649
* https://github.com/Wikia/app/pull/10731
* https://github.com/Wikia/chat/pull/30

## Reviewers

@nmonterroso @owend @wladekb @pchojnacki @dianafa , whoever gets here first :-)

### CODE REVIEW

**Comment by owend** [comment]
yeah, lgtm

**Comment by mixth-sense** [comment]
It might be a good idea to improve the user experience and let them know that the message has been too long and could not be displayed.

**Comment by macbre** [comment]
:+1:

**Comment by Edward-Nigma** [comment]
Bravo, it only took four years for that to get patched. I've been abusing that for four years. I guess that I had to crash a few chat rooms before anyone noticed

**Pull request merged**
