### PR TITLE
Chat: get rid of ProxyServer setting

### PR DESCRIPTION
**Pull request by macbre**
[PLATFORM-1928](https://wikia-inc.atlassian.net/browse/PLATFORM-1928)

Was commented out in 819f4e7

Once that's merged we can get rid of `ProxyServer` entries in `ChatConfig.json` -> https://github.com/Wikia/config/pull/1633

@owend / @garthwebb / @artursitarski

### CODE REVIEW

**Comment by artursitarski** [comment]
:+1:

**Comment by owend** [comment]
LGTM :+1:  Can we deploy this at low peak time (10am-noon GMT)?

**Comment by garthwebb** [comment]
LGTM, though this is essentially a NOOP since it seems like WIKIA_PROXY wasn't being used anywhere, right?  That is, it was already commented out in the only place it was used.

**Comment by macbre** [comment]
Yep, it became no-op after being commented out.

**Pull request merged**
