### PR TITLE
SUS-382 Config refactoring to use environment variables

### PR DESCRIPTION
**Pull request by pchojnacki**
Configuration via external file that describes the whole system is hard to grasp when setting up local instance and when changing configuration requires more coordination when updating configuration.

### CODE REVIEW

**Comment by pauloslund** [comment]
Really like this as it makes configuration so much easier (I'm actually already using it for unit testing). One quick thing though, it seems you've missed some references to config variable when they use `self.config` instead of `this.config` as seen here: https://github.com/Wikia/chat/blob/config_refactor/storage.js#L190

**Comment by pchojnacki** [comment]
Thanks I'll fix that.
I'll also add label that this shouldn't be merge yet because there are some dependencies in chef that are not yet in place so merge would cause chat to be undeployable.

**Comment by bulaszenko** [comment]
Checked works good moving ticket to done column

**Pull request merged**
